# Generated by Django 4.2.5 on 2023-10-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=64)),
                ('product_description', models.CharField(max_length=1024)),
                ('product_price', models.FloatField()),
                ('product_img_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=512)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.product')),
            ],
        ),
    ]
