# Generated by Django 4.2.5 on 2023-10-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('author', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=512)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
